
trigger:
  #When the master branch receives a commit, and a file changes in a specific folder this pipeline will run
  branches:
    include:
    - master
    - dev
  paths:
    exclude:
    - README.md # Don't run pipeline if we're just updating docs

variables:
  vmImageName: "windows-latest"
  serviceConnectionName: "DevOps-to-JeffMPN"

pool:
  vmImage: $(vmImageName)

steps:

  # Create Automation Account. This script will call and create RunAs account if needed, using KeyVault certificate.
  # Your DevOps service connection must be "Application Administrator" on the tenant for this to work properly
  # Your DevOps service connection must be "Owner" on the subscription for this to work properly
- task: AzurePowerShell@4
  displayName: 'Azure PowerShell script: Create Automation Account'
  inputs:
    azureSubscription: $(serviceConnectionName)
    ScriptPath: 'Create-AutomationAccount.ps1'
    azurePowerShellVersion: LatestVersion
    #workingDirectory: 'DSC/'

# Upload Configuration and start Compilation job
- task: AzurePowerShell@4
  displayName: 'Azure PowerShell script: Run DSC Input'
  inputs:
    azureSubscription: $(serviceConnectionName)
    ScriptPath: 'dsc_Input.ps1'
    azurePowerShellVersion: LatestVersion
    #workingDirectory: 'DSC/'